[package]
name = "counter_without_macros_macos"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "counter_without_macros_macos"
path = "src/main.rs"

[dependencies]
leptos = { path = "../../leptos", features = ["native-ui"] }
tachys = { path = "../../tachys", features = ["native-ui"] }
