[package]
name = "leptos_uikit"
version = "0.1.0"
authors = ["Seph Gentle"]
license = "MIT"
description = "UIKit native UI port for the leptos-mac fork (iOS)."
rust-version.workspace = true
edition.workspace = true

[lib]
name = "leptos_uikit"

[dependencies]
renderer = { workspace = true }
reactive_graph = { workspace = true, features = ["effects"] }
leptos = { workspace = true }
leptos_macro = { workspace = true }
either_of = { workspace = true }
oco_ref = { workspace = true }
send_wrapper = { workspace = true, default-features = true }

[target.'cfg(target_os = "ios")'.dependencies]
ios_dom = { path = "../dom", version = "0.1.0" }
objc2 = "0.6"
objc2-foundation = "0.3"
objc2-ui-kit = "0.3"
any_spawner = { workspace = true }

[features]
default = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(leptos_debuginfo)',
] }
