[package]
name = "greeter_macos"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "greeter_macos"
path = "src/main.rs"

[target.'cfg(target_os = "macos")'.dependencies]
leptos = { path = "../../leptos", default-features = false }
reactive_graph = { path = "../../reactive_graph", features = ["effects"] }
tachys = { path = "../../tachys", features = ["reactive_graph"] }
