[package]
name = "todomvc"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "todomvc"
path = "src/main.rs"

[dependencies]
leptos = { path = "../../leptos", features = ["native-ui"] }
cocoa_dom = { path = "../../cocoa_dom" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1", features = ["v4", "serde"] }
