[package]
name = "counter_gtk"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "counter"
path = "src/main.rs"

[dependencies]
leptos = { package = "leptos_gtk", path = "../../leptos_gtk" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(leptos_debuginfo)',
] }
