[package]
name = "transition_macos"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "transition"
path = "src/main.rs"

[dependencies]
leptos = { package = "leptos_cocoa", path = "../../leptos_cocoa" }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
tokio = { version = "1", features = ["rt-multi-thread", "time", "net", "io-util", "macros", "sync"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1"
